### ISSUE TITLE
Experimentation details

### ISSUE THREAD

**Issue by cmakelabs** [lis-epfl/apg_trajectory_tracking#8]
Thank you for your efforts and the impressive work,
We are trying to write a ROS interface for the model,  Is it possible to try the model in reality, what FCUs would be compatible?

**Comment by vwueest** [comment]
Hey @cmakelabs, yes it's certainly possible to try the model in reality since we are sending commands that contain thrust & desired angular rates (as mentioned [here](https://github.com/lis-epfl/apg_trajectory_tracking/blob/main/training_details.pdf)), which is a common input to FCUs. You can check the drone RPG uses for racing (see [here](https://rpg.ifi.uzh.ch/docs/ScienceRobotics22_Foehn.pdf) for details and [here](https://agilicious.readthedocs.io/en/latest/index.html)). It would also work with a drone that has a PX4 autopilot with MavROS (see for example [here](https://docs.px4.io/main/en/ros/mavros_offboard_python.html)). I'm sure that there are other FCUs that allow it too though. Best of luck
