### ISSUE TITLE
Integrating Path Planning with RL for Unseen Trajectories

### ISSUE THREAD

**Issue by abdul-mannan-khan** [lis-epfl/apg_trajectory_tracking#9]
Hello @vwueest,

I am working to adapt your RL algorithm for an unknown dynamic path planning to reach a target point avoiding obstacles. I am facing challenges in integrating this path planning module h into the existing framework.  I have checked `generate_trajectory.py` but it seems that it is generating trajectory for traning. Could you guide me on where in the codebase this integration is most feasible?  

I am also having a confusion whethter the model is able to handle trajectories it hasn't been explicitly trained on. Does the current RL model generalize effectively to new, unseen trajectories? 

Your insights on these issues would be greatly appreciated.

Thank you!

**Comment by NinaWie** [comment]
Hi @abdul-mannan-khan, your work sounds interesting! Do I understand correctly: You have an own path planning module and would like to integrate it into our framework, such that our model can track your trajectory? Our framework does generalize to new trajectories, since it is trained on randomly generated trajectories. Those random trajectories are generated in the `generate_trajectory.py` as you saw. 
It should be easy to replace them with other trajectories. I would start with a pretrained model and modify the inference code in `scripts/evaluate_drone.py` to load your trajectories. This is where we load a trajectory in the script: https://github.com/lis-epfl/apg_trajectory_tracking/blob/76fd27ac08450c4ea3c01cb633a58a892129469c/scripts/evaluate_drone.py#L120
I hope that helps, let me know if you have further questions!

**Comment by abdul-mannan-khan** [comment]
Dear @NinaWie, This is exactly what I was looking for.  Basically, I do not want to run the code on the same trajectory it is trained for. Thank you so much for your response.
